services:
  telegram-bot:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - /mnt/hdd:/app/downloads
    restart: unless-stopped